// AUTO-GENERATED by tools/gen-music-manifest.mjs. Do not edit by hand.
export type MusicPhase = 'lobby' | 'writing' | 'wrapup';

// Paths are public-relative; wrap with asset() for basePath at use.
export const MUSIC_TRACKS: Record<MusicPhase, string[]> = {
  "lobby": [
    "/music/lobby/Nice and Friendly Story.mp3"
  ],
  "writing": [
    "/music/writing/AudioHarvest_Warm-Acoustic-Guitar_Short-01_69sec.mp3",
    "/music/writing/Sentimental Acoustic.mp3",
    "/music/writing/Warm Acoustic Inspiring.mp3",
    "/music/writing/Welcome Home.mp3"
  ],
  "wrapup": [
    "/music/wrapup/Acoustic Chill.mp3"
  ]
};

export const hasAnyMusic = true;
